[package]
name = "editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = {git = "https://github.com/jeaye/ncurses-rs"}
# gag crate allows to redirect stdout to file
gag = "1.0.0"
